services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/src